//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.07 at 10:29:05 AM EST 
//

package com.ebay.shopping.categories.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Contains details about a category.
 * 
 * 
 * <p>
 * Java class for CategoryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CategoryLevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CategoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CategoryParentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CategoryParentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItemCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CategoryNamePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CategoryIDPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LeafCategory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryType", propOrder = { "categoryID", "categoryLevel", "categoryName", "categoryParentID",
		"categoryParentName", "itemCount", "categoryNamePath", "categoryIDPath", "leafCategory" })
public class CategoryType {

	@XmlElement(name = "CategoryID")
	protected String categoryID;
	@XmlElement(name = "CategoryLevel")
	protected Integer categoryLevel;
	@XmlElement(name = "CategoryName")
	protected String categoryName;
	@XmlElement(name = "CategoryParentID")
	protected String categoryParentID;
	@XmlElement(name = "CategoryParentName")
	protected String categoryParentName;
	@XmlElement(name = "ItemCount")
	protected Integer itemCount;
	@XmlElement(name = "CategoryNamePath")
	protected String categoryNamePath;
	@XmlElement(name = "CategoryIDPath")
	protected String categoryIDPath;
	@XmlElement(name = "LeafCategory")
	protected Boolean leafCategory;

	/**
	 * Gets the value of the categoryID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryID() {
		return categoryID;
	}

	/**
	 * Sets the value of the categoryID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryID(String value) {
		this.categoryID = value;
	}

	/**
	 * Gets the value of the categoryLevel property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCategoryLevel() {
		return categoryLevel;
	}

	/**
	 * Sets the value of the categoryLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCategoryLevel(Integer value) {
		this.categoryLevel = value;
	}

	/**
	 * Gets the value of the categoryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * Sets the value of the categoryName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryName(String value) {
		this.categoryName = value;
	}

	/**
	 * Gets the value of the categoryParentID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryParentID() {
		return categoryParentID;
	}

	/**
	 * Sets the value of the categoryParentID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryParentID(String value) {
		this.categoryParentID = value;
	}

	/**
	 * Gets the value of the categoryParentName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryParentName() {
		return categoryParentName;
	}

	/**
	 * Sets the value of the categoryParentName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryParentName(String value) {
		this.categoryParentName = value;
	}

	/**
	 * Gets the value of the itemCount property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getItemCount() {
		return itemCount;
	}

	/**
	 * Sets the value of the itemCount property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setItemCount(Integer value) {
		this.itemCount = value;
	}

	/**
	 * Gets the value of the categoryNamePath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryNamePath() {
		return categoryNamePath;
	}

	/**
	 * Sets the value of the categoryNamePath property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryNamePath(String value) {
		this.categoryNamePath = value;
	}

	/**
	 * Gets the value of the categoryIDPath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryIDPath() {
		return categoryIDPath;
	}

	/**
	 * Sets the value of the categoryIDPath property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryIDPath(String value) {
		this.categoryIDPath = value;
	}

	/**
	 * Gets the value of the leafCategory property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isLeafCategory() {
		return leafCategory;
	}

	/**
	 * Sets the value of the leafCategory property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setLeafCategory(Boolean value) {
		this.leafCategory = value;
	}

}
